language: node_js
node_js:
- node
git:
  depth: false
script:
- npm run test
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIXAPOLMFA5OFOBDA
  secret_access_key:
    secure: 3CJWzHp2wtj/n/KcljyrrytE/iKlMy5R/B0Hw/EWhVT+Fj13YsY29v2cciYf9vNWn7O10ogldhk4mdfXAL+thFt0cS3J+w+DWeA8KVeLxwTW2f/1TwFpOhCwakPu0IG3dpixNxHDcC5fnV9DXicsrbqL6ZtLU8zNs0PZdMuwxzviq64S4wQaGNU2BNR69oC8wPllnvG3cENCJtu+ne4FK6KBVzUQlXYS34gOVy0+887mMBZ0IvlzGG9o8tFf9PQniS5nTbE22vkKxE1I0NTyBaa4Fq2KZaslaaTVL20WJyBs7qY31zgpCXva2LuK8NltK9wDcNfCpBukQmE0vZrDesplW7BPg4CmRoEH6yWQJamSUbyY/yuBnTemkZmG/gSUgRnrDfPeUGeoF2ZcxnT6IKuCc/Ni7koNDEeHspmF6zbtTITOvOpeWw7ZdMP7sqa45VbVQKvLuALEKSxE44otppsGWgiky3eaoHGdGiiK1WZwN5zjLx+G7TFeaK7iajaDgfxDxanNqrex2PcUTIDo82XvZd94prZiRLy0M7D3gmZDhrh3ruRhd8StFaP+UvvMW7waBfrX3a3GdtJ3czqscFPtQ4lP0r7OMFIkkrxTqdCmDNtXvCfcJDBARhC1VKPwARvemQna9sykA1a4sTXOu9bFda8Ak0QWO07mq0/n1ns=
  bucket: docking.evanlissoos.com
  region: us-east-2
  local-dir: build
